// <auto-generated />
using System;
using MentoraX.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MentoraX.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MentoraXDbContext))]
    [Migration("20260422155848_AddLearningMaterialStudyPlansRelation")]
    partial class AddLearningMaterialStudyPlansRelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MentoraX.Domain.Entities.LearningMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("EstimatedDurationMinutes")
                        .HasColumnType("int");

                    b.Property<int>("MaterialType")
                        .HasColumnType("int");

                    b.Property<string>("Tags")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("LearningMaterials", (string)null);
                });

            modelBuilder.Entity("MentoraX.Domain.Entities.MobileDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceToken")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "DeviceToken")
                        .IsUnique();

                    b.ToTable("MobileDevices", (string)null);
                });

            modelBuilder.Entity("MentoraX.Domain.Entities.StudyPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DailyTargetMinutes")
                        .HasColumnType("int");

                    b.Property<Guid>("LearningMaterialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LearningMaterialId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LearningMaterialId");

                    b.HasIndex("LearningMaterialId1");

                    b.HasIndex("UserId");

                    b.ToTable("StudyPlans", (string)null);
                });

            modelBuilder.Entity("MentoraX.Domain.Entities.StudyProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<double>("EasinessFactor")
                        .HasPrecision(5, 2)
                        .HasColumnType("float(5)");

                    b.Property<int>("FailureCount")
                        .HasColumnType("int");

                    b.Property<int>("IntervalDays")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastReviewedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LearningMaterialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NextReviewAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("RepetitionCount")
                        .HasColumnType("int");

                    b.Property<Guid>("StudyPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SuccessStreak")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LearningMaterialId");

                    b.HasIndex("StudyPlanId");

                    b.HasIndex("UserId", "LearningMaterialId", "StudyPlanId")
                        .IsUnique();

                    b.ToTable("StudyProgresses", (string)null);
                });

            modelBuilder.Entity("MentoraX.Domain.Entities.StudySession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ActualDurationMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DifficultyScore")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("LearningMaterialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int?>("QualityScore")
                        .HasColumnType("int");

                    b.Property<string>("ReviewNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("ScheduledAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("StudyPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StudyProgressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LearningMaterialId");

                    b.HasIndex("StudyPlanId");

                    b.HasIndex("StudyProgressId");

                    b.HasIndex("UserId", "ScheduledAtUtc", "IsCompleted");

                    b.ToTable("StudySessions", (string)null);
                });

            modelBuilder.Entity("MentoraX.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("MentoraX.Domain.Entities.LearningMaterial", b =>
                {
                    b.HasOne("MentoraX.Domain.Entities.User", "User")
                        .WithMany("Materials")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MentoraX.Domain.Entities.MobileDevice", b =>
                {
                    b.HasOne("MentoraX.Domain.Entities.User", "User")
                        .WithMany("MobileDevices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MentoraX.Domain.Entities.StudyPlan", b =>
                {
                    b.HasOne("MentoraX.Domain.Entities.LearningMaterial", "LearningMaterial")
                        .WithMany()
                        .HasForeignKey("LearningMaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MentoraX.Domain.Entities.LearningMaterial", null)
                        .WithMany("StudyPlans")
                        .HasForeignKey("LearningMaterialId1");

                    b.HasOne("MentoraX.Domain.Entities.User", "User")
                        .WithMany("StudyPlans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LearningMaterial");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MentoraX.Domain.Entities.StudyProgress", b =>
                {
                    b.HasOne("MentoraX.Domain.Entities.LearningMaterial", "LearningMaterial")
                        .WithMany("StudyProgresses")
                        .HasForeignKey("LearningMaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MentoraX.Domain.Entities.StudyPlan", "StudyPlan")
                        .WithMany("StudyProgresses")
                        .HasForeignKey("StudyPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MentoraX.Domain.Entities.User", "User")
                        .WithMany("StudyProgresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LearningMaterial");

                    b.Navigation("StudyPlan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MentoraX.Domain.Entities.StudySession", b =>
                {
                    b.HasOne("MentoraX.Domain.Entities.LearningMaterial", "LearningMaterial")
                        .WithMany("StudySessions")
                        .HasForeignKey("LearningMaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MentoraX.Domain.Entities.StudyPlan", "StudyPlan")
                        .WithMany("StudySessions")
                        .HasForeignKey("StudyPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MentoraX.Domain.Entities.StudyProgress", "StudyProgress")
                        .WithMany("StudySessions")
                        .HasForeignKey("StudyProgressId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MentoraX.Domain.Entities.User", "User")
                        .WithMany("StudySessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LearningMaterial");

                    b.Navigation("StudyPlan");

                    b.Navigation("StudyProgress");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MentoraX.Domain.Entities.LearningMaterial", b =>
                {
                    b.Navigation("StudyPlans");

                    b.Navigation("StudyProgresses");

                    b.Navigation("StudySessions");
                });

            modelBuilder.Entity("MentoraX.Domain.Entities.StudyPlan", b =>
                {
                    b.Navigation("StudyProgresses");

                    b.Navigation("StudySessions");
                });

            modelBuilder.Entity("MentoraX.Domain.Entities.StudyProgress", b =>
                {
                    b.Navigation("StudySessions");
                });

            modelBuilder.Entity("MentoraX.Domain.Entities.User", b =>
                {
                    b.Navigation("Materials");

                    b.Navigation("MobileDevices");

                    b.Navigation("StudyPlans");

                    b.Navigation("StudyProgresses");

                    b.Navigation("StudySessions");
                });
#pragma warning restore 612, 618
        }
    }
}
